### ISSUE TITLE
Touch not working when timeout is other than 0

### ISSUE THREAD

**Issue by jacobsjensen** [keeganbrown/cycle#4]
Hi, is it intended behavior that touch is not working when timeout is other than 0?
Would be great, if an option to "pause on touch", so that a slideshow would be touch enabled :-)

And if it's me who got it all wrong, my apologies :-)

BTW Great initiative!

**Comment by keeganbrown** [comment]
Touch should work when timeout is other than 0, however stopping a transition with a touch event in the middle of the transition was causing all kinds of problems, so that has been prevented. Not optimal, I know, but neither is jQuery's animation engine. I was considering rewriting this bit with TweenLite.js or some other animation library that supports time scrubbing of animation, but that's a whole other can of worms.

For what it's worth if the touch support is outright breaking when timeout is > 0, that is an error and should be fixed.

**Comment by keeganbrown** [comment]
I hope that I've fixed this. Please download the latest and LMK if there's any issues.

**Comment by jacobsjensen** [comment]
Hi Keegan,

Works really well! Just installed it on a responsive site with a fluid size cycle container. Really nice!!!
